### ISSUE TITLE
gsl gem

### ISSUE THREAD

**Issue by minad** [david-macmahon/rb-gsl#8]
Hi David,

is this repository the source of the gsl gem? There is the fork https://github.com/blackwinter/rb-gsl which is released as rb-gsl gem. The rb-gsl gem supports ruby2 and other improvements. Maybe we could unite the two again under the name gsl? Ping @blackwinter @v0dro @mohawkjohn @agarie

Best,
Daniel

**Comment by v0dro** [comment]
from what I can see this fork seems to have a lot of bugfixes etc. that are absent in blackwinter/rb-gsl. Uniting both would be great.

**Comment by minad** [comment]
I think blackwinter's is a fork from this one

**Comment by david-macmahon** [comment]
I think that's right.  I would love to see a unified version.  I also have some un-pushed changes that I should probably get around to pushing at some point.  Unfortunately, I have very little time to work on this, but if anyone wants to work on unifying thing I'd be happy to support/encourage that.

Dave

**Comment by minad** [comment]
Ok. Sounds great. I think blackwinters fork is the most recent one. So I would suggest we continue from there.

Could you give me access to this repository and the gsl gem?

We (sciruby) would do the following:

1. Release new gsl 1.16.1 based on rb-gsl with ruby2 support and optional narray support
2. Release new rb-gsl 1.16.1 which will depend on gsl to unify both.

Later we would add support for nmatrix so that we support both narray and nmatrix. Then I would also merge your unpushed changes.

Am 21. Juni 2015 16:48:05 MESZ, schrieb david-macmahon <notifications@github.com>:

**Comment by blackwinter** [comment]
@minad: I imported the code from the [gsl](https://rubygems.org/gems/gsl) gem so it's a fork in the technical sense, just not in GitHub's sense; cf. blackwinter/rb-gsl#14.

@v0dro: Not sure what bug fixes you mean. I imported version 1.15.3 in November 2013, since then nothing has happened in this repository.

**Comment by minad** [comment]
@david-macmahon @blackwinter @v0dro I imported the current rb-gsl to https://github.com/SciRuby/rb-gsl and added you to the repository

**Comment by v0dro** [comment]
@blackwinter I didn't see David's commits in your repo so I thought his repo might have extra stuff that was missed out in blackwinter/rb-gsl.

Thank you @minad.

**Comment by minad** [comment]
ping @david-macmahon

**Comment by minad** [comment]
Great thx. Could you also add me to the gem so that I can push a new release there? I just released a new rb-gsl gem but it would be nice to also unit the gems at rubygems.org as described above.

Are you fine if development continues at https://github.com/SciRuby/rb-gsl? You have access there.

**Comment by david-macmahon** [comment]
Just added you as gem owner too.  I'm fine having development continue at SciRuby.  I think it's a good thing!

Thanks,
Dave

**Comment by minad** [comment]
thx!
